language: objective-c
osx_image: xcode10
script:
    - xcodebuild -project Tests/HTTPStatusCodes.xcodeproj -scheme HTTPStatusCodes clean build test
    - xcodebuild -project Tests/HTTPStatusCodes.xcodeproj -scheme HTTPStatusCodes -destination "platform=iOS Simulator,name=iPhone X" clean build test
    - xcodebuild -project Tests/HTTPStatusCodes.xcodeproj -scheme HTTPStatusCodes -destination "platform=tvOS Simulator,name=Apple TV 4K" clean build test
